import React, { useState, useEffect } from "react";
import QRCode from "qrcode";
import {
  CreditCard,
  CheckCircle2,
  Trash2,
  ExternalLink,
  Smartphone,
  QrCode,
  Send,
  Copy,
  Check,
  Search,
  RefreshCw,
  Building,
  Sparkles,
  AlertCircle,
  Plus,
  Minus,
  Store,
  FileText,
  DollarSign,
  Briefcase
} from "lucide-react";

// Types
interface CartItem {
  id: string;
  name: string;
  price: number;
  qty: number;
  category: string;
}

interface PaymentRequest {
  id: string;
  merchantName: string;
  clientName: string;
  clientPhone?: string;
  items: CartItem[];
  customDescription?: string;
  subtotal: number;
  tax: number;
  totalDue: number;
  paymentMethodType: "sms" | "qr" | "link";
  status: "Pending" | "Paid";
  createdDate: string;
  payLink: string;
  completedDate?: string;
}

// Initial default inventory items for the arbitrary store
const DEFAULT_INVENTORY: CartItem[] = [
  { id: "blazer", name: "Tailored Wool Blend Blazer", price: 1850.00, qty: 1, category: "Apparel" },
  { id: "shirt", name: "Premium Egyptian Cotton Shirt", price: 690.00, qty: 1, category: "Apparel" },
  { id: "shoes", name: "Handcrafted Leather Loafers", price: 2490.00, qty: 1, category: "Footwear" },
  { id: "belt", name: "Full-Grain Leather Dress Belt", price: 420.00, qty: 1, category: "Accessories" }
];

export default function PaymentInterface() {
  // Merchant Configuration: Strictly Apparel Co.
  const storeName = "Apparel Co.";

  // Current order cart items
  const [cartItems, setCartItems] = useState<CartItem[]>(() => 
    DEFAULT_INVENTORY.map(item => ({ ...item, qty: 0 }))
  );
  
  // State: Underwriting / Tax Settings
  const [taxRate] = useState<number>(0.15); // 15% South African standard VAT

  // State: Payment requests generated by merchant using Zen-i
  const [paymentRequests, setPaymentRequests] = useState<PaymentRequest[]>([
    {
      id: "PAY-80124",
      merchantName: "Apparel Co.",
      clientName: "Njabulo Dlamini",
      clientPhone: "+27 (82) 554-9120",
      items: [
        { id: "blazer", name: "Tailored Wool Blend Blazer", price: 1850.00, qty: 1, category: "Apparel" }
      ],
      subtotal: 1850.00,
      tax: 277.50,
      totalDue: 2127.50,
      paymentMethodType: "sms",
      status: "Paid",
      createdDate: "2026-06-25",
      payLink: "https://zen-i.co.za/pay/PAY-80124",
      completedDate: "2026-06-25"
    },
    {
      id: "PAY-80125",
      merchantName: "Apparel Co.",
      clientName: "Lerato Modise",
      clientPhone: "+27 (71) 321-4560",
      items: [
        { id: "shoes", name: "Handcrafted Leather Loafers", price: 2490.00, qty: 1, category: "Footwear" },
        { id: "belt", name: "Full-Grain Leather Dress Belt", price: 420.00, qty: 1, category: "Accessories" }
      ],
      subtotal: 2910.00,
      tax: 436.50,
      totalDue: 3346.50,
      paymentMethodType: "qr",
      status: "Pending",
      createdDate: "2026-06-26",
      payLink: "https://zen-i.co.za/pay/PAY-80125"
    },
    {
      id: "PAY-80126",
      merchantName: "Apparel Co.",
      clientName: "Adrian van der Merwe",
      items: [
        { id: "shirt", name: "Premium Egyptian Cotton Shirt", price: 690.00, qty: 2, category: "Apparel" }
      ],
      subtotal: 1380.00,
      tax: 207.00,
      totalDue: 1587.00,
      paymentMethodType: "link",
      status: "Pending",
      createdDate: "2026-06-26",
      payLink: "https://zen-i.co.za/pay/PAY-80126"
    }
  ]);

  // Merchant link generator states
  const [clientName, setClientName] = useState("");
  const [clientPhone, setClientPhone] = useState("");
  const [paymentMethodType, setPaymentMethodType] = useState<"sms" | "qr" | "link">("sms");
  const [quickAmountMode, setQuickAmountMode] = useState<"inventory" | "custom">("inventory");
  const [customAmount, setCustomAmount] = useState<string>("");
  const [customReason, setCustomReason] = useState("");
  
  // Feedback States
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [newlyCreatedRequest, setNewlyCreatedRequest] = useState<PaymentRequest | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<"All" | "Pending" | "Paid">("All");

  // Client-side QR Code state
  const [qrDataUrl, setQrDataUrl] = useState<string>("");
  const [selectedRequestForQr, setSelectedRequestForQr] = useState<PaymentRequest | null>(null);
  const [selectedQrDataUrl, setSelectedQrDataUrl] = useState<string>("");

  useEffect(() => {
    if (newlyCreatedRequest && newlyCreatedRequest.paymentMethodType === "qr") {
      QRCode.toDataURL(newlyCreatedRequest.payLink, {
        width: 250,
        margin: 2,
        color: {
          dark: "#4f46e5", // Indigo-600
          light: "#ffffff"
        }
      })
      .then(url => setQrDataUrl(url))
      .catch(err => console.error("Error generating QR:", err));
    } else {
      setQrDataUrl("");
    }
  }, [newlyCreatedRequest]);

  useEffect(() => {
    if (selectedRequestForQr) {
      QRCode.toDataURL(selectedRequestForQr.payLink, {
        width: 300,
        margin: 2,
        color: {
          dark: "#1e1b4b", // Indigo-950
          light: "#ffffff"
        }
      })
      .then(url => setSelectedQrDataUrl(url))
      .catch(err => console.error("Error generating ledger QR:", err));
    } else {
      setSelectedQrDataUrl("");
    }
  }, [selectedRequestForQr]);

  // Cart helper functions
  const updateQty = (id: string, delta: number) => {
    setCartItems(prev => prev.map(item => {
      if (item.id === id) {
        return { ...item, qty: Math.max(0, item.qty + delta) };
      }
      return item;
    }));
  };

  const resetOrderQty = () => {
    setCartItems(DEFAULT_INVENTORY.map(item => ({ ...item, qty: 0 })));
  };

  // Mathematical calculations for current cart
  const subtotal = quickAmountMode === "inventory" 
    ? cartItems.reduce((acc, item) => acc + (item.price * item.qty), 0)
    : parseFloat(customAmount) || 0;
  const tax = subtotal * taxRate;
  const totalDue = subtotal + tax;

  // Clipboard copies helper
  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopiedId(id);
      setTimeout(() => setCopiedId(null), 2000);
    }).catch(() => {
      setCopiedId(id);
      setTimeout(() => setCopiedId(null), 2000);
    });
  };

  // Generate Payment Request from Merchant Dashboard
  const handleGenerateRequest = () => {
    if (!clientName.trim()) {
      alert("Please enter the Client Name.");
      return;
    }
    if (paymentMethodType === "sms" && !clientPhone.trim()) {
      alert("Mobile phone number is required to send payment link via SMS.");
      return;
    }
    if (quickAmountMode === "custom" && (!customAmount || parseFloat(customAmount) <= 0)) {
      alert("Please enter a valid invoice amount.");
      return;
    }
    if (quickAmountMode === "inventory" && subtotal <= 0) {
      alert("Please increase quantity of at least one item from the inventory list.");
      return;
    }

    setIsGenerating(true);

    setTimeout(() => {
      const generatedId = "PAY-" + Math.floor(100000 + Math.random() * 900000);
      const dateStr = new Date().toISOString().split('T')[0];
      
      let reqItems: CartItem[] = [];
      if (quickAmountMode === "inventory") {
        reqItems = cartItems.filter(item => item.qty > 0);
      } else {
        reqItems = [{
          id: `custom-inv-${Date.now()}`,
          name: customReason.trim() || "Bespoke Services Rendered",
          price: parseFloat(customAmount),
          qty: 1,
          category: "Custom"
        }];
      }

      const newRequest: PaymentRequest = {
        id: generatedId,
        merchantName: storeName,
        clientName: clientName.trim(),
        clientPhone: paymentMethodType === "sms" ? clientPhone.trim() : undefined,
        items: reqItems,
        customDescription: quickAmountMode === "custom" ? customReason.trim() : undefined,
        subtotal: subtotal,
        tax: tax,
        totalDue: totalDue,
        paymentMethodType: paymentMethodType,
        status: "Pending",
        createdDate: dateStr,
        payLink: `https://zen-i.co.za/pay/${generatedId}`
      };

      setPaymentRequests(prev => [newRequest, ...prev]);
      setNewlyCreatedRequest(newRequest);
      setIsGenerating(false);

      // Clear input fields for next request
      setClientName("");
      setClientPhone("");
      setCustomAmount("");
      setCustomReason("");
      resetOrderQty();
    }, 1000);
  };

  // Handle manual marking of requests as Paid
  const handleMarkAsPaid = (id: string) => {
    const today = new Date().toISOString().split('T')[0];
    setPaymentRequests(prev => prev.map(req => {
      if (req.id === id) {
        return {
          ...req,
          status: "Paid",
          completedDate: today
        };
      }
      return req;
    }));
  };

  // Stats for CRM Merchant Dashboard
  const filteredRequests = paymentRequests.filter(req => {
    const matchesSearch = req.clientName.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          req.id.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = statusFilter === "All" || req.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const totalGeneratedAmt = paymentRequests.reduce((acc, req) => acc + req.totalDue, 0);
  const totalCollectedAmt = paymentRequests.filter(req => req.status === "Paid").reduce((acc, req) => acc + req.totalDue, 0);
  const totalPendingAmt = paymentRequests.filter(req => req.status === "Pending").reduce((acc, req) => acc + req.totalDue, 0);
  const conversionRate = paymentRequests.length > 0 
    ? (paymentRequests.filter(req => req.status === "Paid").length / paymentRequests.length) * 100 
    : 0;

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col justify-between font-sans antialiased text-slate-900 selection:bg-indigo-100">
      

      {/* App Workspace Container */}
      <div className="flex-1 flex flex-col max-w-7xl w-full mx-auto p-4 md:p-6 lg:p-8 gap-6">
        
        {/* Workspace Segment Control Header */}
        <div className="bg-white rounded-2xl border border-slate-200 p-5 md:p-6 flex flex-col md:flex-row items-center justify-between gap-4 shadow-xs">
          <div className="flex items-center gap-3.5 w-full md:w-auto">
            <div className="w-12 h-12 bg-indigo-600 rounded-2xl flex items-center justify-center text-white shrink-0 shadow-md shadow-indigo-100">
              <Store className="w-6 h-6" />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <h1 className="text-xl font-extrabold text-slate-800 tracking-tight flex items-center gap-2">
                  <span>{storeName}</span>
                </h1>
                <span className="text-[10px] bg-indigo-50 text-indigo-700 font-extrabold px-2.5 py-0.5 rounded-full border border-indigo-200">
                  via Zen-i Open Payments
                </span>
              </div>
              <p className="text-slate-500 text-xs font-semibold mt-1">
                Generate and dispatch digital split-payment links directly to your clients.
              </p>
            </div>
          </div>
          
          <div className="flex items-center gap-3 self-end md:self-auto">
            <div className="text-right hidden sm:block">
              <p className="text-[10px] uppercase font-bold text-slate-400">Merchant Account ID</p>
              <p className="text-xs font-mono font-bold text-slate-700">MID-99218-ZAR</p>
            </div>
          
          </div>
        </div>

        {/* MERCHANT TERMINAL PANEL */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          
          {/* Create Payment Request Form Block (Left, Spans 5) */}
          <div className="lg:col-span-5 bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden flex flex-col justify-between">
            
            <div className="p-5 md:p-6 border-b border-slate-100 bg-slate-50/50">
              <span className="text-[10px] font-extrabold text-indigo-600 uppercase tracking-wider block">Open Payments API Integration</span>
              <h3 className="text-lg font-bold text-slate-800 mt-0.5">Generate Instant Invoice Link</h3>
              <p className="text-[11px] text-slate-400 mt-1">Configure client particulars and pay-out channels</p>
            </div>

            <div className="p-5 md:p-6 space-y-5">
              
              {/* Client Information Form */}
              <div className="space-y-3">
                <div className="space-y-1.5">
                  <label className="text-[10px] font-extrabold text-slate-500 uppercase tracking-wider">Client Legal Name</label>
                  <input
                    type="text"
                    value={clientName}
                    onChange={(e) => setClientName(e.target.value)}
                    placeholder="e.g. Sanele Khumalo"
                    className="w-full border border-slate-200 rounded-xl px-3 py-2.5 text-xs font-medium focus:outline-none focus:ring-2 focus:ring-indigo-100 focus:border-indigo-600 bg-slate-50"
                  />
                </div>

                {/* Distribution Tabs */}
                <div className="space-y-1.5">
                  <label className="text-[10px] font-extrabold text-slate-500 uppercase tracking-wider">Link Delivery Channel</label>
                  <div className="grid grid-cols-3 gap-2">
                    <button
                      type="button"
                      onClick={() => setPaymentMethodType("sms")}
                      className={`py-2 px-2.5 rounded-xl border text-[11px] font-bold flex flex-col items-center justify-center gap-1 transition-all ${
                        paymentMethodType === "sms"
                          ? "border-indigo-600 bg-indigo-50/20 text-indigo-700"
                          : "border-slate-200 text-slate-600 hover:border-indigo-200 bg-slate-50/50"
                      }`}
                    >
                      <Smartphone className="w-4 h-4" />
                      SMS Text
                    </button>
                    <button
                      type="button"
                      onClick={() => setPaymentMethodType("qr")}
                      className={`py-2 px-2.5 rounded-xl border text-[11px] font-bold flex flex-col items-center justify-center gap-1 transition-all ${
                        paymentMethodType === "qr"
                          ? "border-indigo-600 bg-indigo-50/20 text-indigo-700"
                          : "border-slate-200 text-slate-600 hover:border-indigo-200 bg-slate-50/50"
                      }`}
                    >
                      <QrCode className="w-4 h-4" />
                      QR Scan
                    </button>
                    <button
                      type="button"
                      onClick={() => setPaymentMethodType("link")}
                      className={`py-2 px-2.5 rounded-xl border text-[11px] font-bold flex flex-col items-center justify-center gap-1 transition-all ${
                        paymentMethodType === "link"
                          ? "border-indigo-600 bg-indigo-50/20 text-indigo-700"
                          : "border-slate-200 text-slate-600 hover:border-indigo-200 bg-slate-50/50"
                      }`}
                    >
                      <ExternalLink className="w-4 h-4" />
                      Direct Link
                    </button>
                  </div>
                </div>

                {/* Client Phone for SMS Mode */}
                {paymentMethodType === "sms" && (
                  <div className="space-y-1.5 animate-fade-in">
                    <label className="text-[10px] font-extrabold text-slate-500 uppercase tracking-wider">Client Mobile Number</label>
                    <div className="relative">
                      <span className="absolute left-3 top-2.5 text-xs text-slate-400 font-bold font-mono">+27</span>
                      <input
                        type="text"
                        value={clientPhone}
                        onChange={(e) => setClientPhone(e.target.value)}
                        placeholder=" (82) 441-2394"
                        className="w-full border border-slate-200 rounded-xl pl-11 pr-3 py-2.5 text-xs font-mono font-bold focus:outline-none focus:ring-2 focus:ring-indigo-100 focus:border-indigo-600 bg-slate-50"
                      />
                    </div>
                    <p className="text-[10px] text-slate-400 italic">Enter customer South African mobile number (without country code)</p>
                  </div>
                )}
              </div>

              {/* Amount Configuration */}
              <div className="space-y-3 pt-2">
                <div className="flex justify-between items-center">
                  <label className="text-[10px] font-extrabold text-slate-500 uppercase tracking-wider">Sourcing of Invoice Value</label>
                  <div className="bg-slate-100 p-0.5 rounded-lg border border-slate-200 flex text-[9px] font-extrabold uppercase">
                    <button
                      onClick={() => setQuickAmountMode("inventory")}
                      className={`px-2 py-1 rounded ${quickAmountMode === "inventory" ? "bg-white text-indigo-600 shadow-xs" : "text-slate-500"}`}
                    >
                      Inventory List
                    </button>
                    <button
                      onClick={() => setQuickAmountMode("custom")}
                      className={`px-2 py-1 rounded ${quickAmountMode === "custom" ? "bg-white text-indigo-600 shadow-xs" : "text-slate-500"}`}
                    >
                      Custom Price
                    </button>
                  </div>
                </div>

                {quickAmountMode === "inventory" ? (
                  /* Inventory Cart Builder */
                  <div className="space-y-2 border border-slate-200 p-3 rounded-xl bg-slate-50/50 max-h-[190px] overflow-y-auto">
                    <div className="flex justify-between text-[10px] font-extrabold text-slate-400 uppercase tracking-widest border-b border-slate-100 pb-1">
                      <span>Available Store Inventory</span>
                      <button
                        onClick={resetOrderQty}
                        className="text-indigo-600 lowercase normal-case font-bold"
                      >
                        Clear Order
                      </button>
                    </div>

                    <div className="space-y-1.5">
                      {cartItems.map(item => (
                        <div key={item.id} className="flex justify-between items-center bg-white p-2 rounded-lg border border-slate-100">
                          <div className="min-w-0">
                            <p className="text-xs font-bold text-slate-800 truncate">{item.name}</p>
                            <p className="text-[10px] text-slate-400 font-medium">R{item.price.toFixed(2)} each</p>
                          </div>
                          <div className="flex items-center gap-2">
                            <div className="flex items-center gap-1 bg-slate-50 border border-slate-200 rounded px-1">
                              <button onClick={() => updateQty(item.id, -1)} className="text-slate-500 hover:text-black font-extrabold text-xs px-1" aria-label="Decrease quantity">-</button>
                              <span className="text-xs font-bold px-1 w-4 text-center">{item.qty}</span>
                              <button onClick={() => updateQty(item.id, 1)} className="text-slate-500 hover:text-black font-extrabold text-xs px-1" aria-label="Increase quantity">+</button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ) : (
                  /* Custom Price Input */
                  <div className="space-y-3 border border-slate-200 p-3 rounded-xl bg-slate-50/50 animate-fade-in">
                    <div className="space-y-1">
                      <label className="text-[10px] font-extrabold text-slate-400 uppercase">Description of Service/Goods</label>
                      <input
                        type="text"
                        value={customReason}
                        onChange={(e) => setCustomReason(e.target.value)}
                        placeholder="e.g. Bespoke Tailoring Services rendered"
                        className="w-full border border-slate-200 rounded-lg px-2.5 py-1.5 text-xs bg-white focus:outline-none"
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-[10px] font-extrabold text-slate-400 uppercase">Direct Settle Amount (R)</label>
                      <div className="relative">
                        <span className="absolute left-3 top-1.5 text-xs font-bold text-indigo-600">R</span>
                        <input
                          type="text"
                          value={customAmount}
                          onChange={(e) => setCustomAmount(e.target.value.replace(/[^0-9.]/g, ""))}
                          placeholder="0.00"
                          className="w-full border border-slate-200 rounded-lg pl-7 pr-3 py-1.5 text-xs bg-white font-mono font-bold focus:outline-none"
                        />
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Mathematical calculation summary block */}
              <div className="bg-indigo-950 text-white rounded-xl p-4 mt-2">
                <div className="flex justify-between items-center text-xs">
                  <span className="text-indigo-200">Subtotal</span>
                  <span className="font-bold text-indigo-100">R{subtotal.toFixed(2)}</span>
                </div>
                <div className="flex justify-between items-center text-xs mt-1">
                  <span className="text-indigo-200">VAT Taxes ({(taxRate * 100).toFixed(0)}%)</span>
                  <span className="font-bold text-indigo-100">R{tax.toFixed(2)}</span>
                </div>
                <div className="border-t border-dashed border-indigo-800 my-2 pt-2 flex justify-between items-end">
                  <span className="text-xs text-indigo-300 font-extrabold uppercase">Underwritten Total</span>
                  <span className="text-xl font-black text-white">R{totalDue.toFixed(2)}</span>
                </div>
              </div>

            </div>

            <div className="p-5 md:p-6 bg-slate-50 border-t border-slate-100">
              <button
                onClick={handleGenerateRequest}
                disabled={isGenerating}
                className="w-full bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white font-bold py-3.5 px-4 rounded-xl text-xs uppercase tracking-wider flex items-center justify-center gap-2 transition-all shadow-md shadow-indigo-100"
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    Generating Secure Link...
                  </>
                ) : (
                  <>
                    <Send className="w-4 h-4" />
                    Generate & Send Link Request
                  </>
                )}
              </button>
            </div>

          </div>

          {/* Link Hub & Interactive CRM Dashboard (Right, Spans 7) */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* Distribution Hub Display if newly generated */}
            {newlyCreatedRequest ? (
              <div className="bg-white rounded-2xl border-2 border-indigo-500 shadow-md overflow-hidden animate-fade-in">
                <div className="bg-indigo-600 text-white px-5 py-4 flex justify-between items-center">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                    <div>
                      <h4 className="font-extrabold text-sm uppercase tracking-wider">Zen-i Link Dispatched</h4>
                      <p className="text-[10px] text-indigo-100">Request code: {newlyCreatedRequest.id}</p>
                    </div>
                  </div>
                  <button
                    onClick={() => setNewlyCreatedRequest(null)}
                    className="text-xs bg-indigo-700 hover:bg-indigo-800 px-2.5 py-1 rounded text-indigo-100 font-bold transition-all"
                  >
                    Dismiss Hub
                  </button>
                </div>

                <div className="p-5 md:p-6 grid grid-cols-1 md:grid-cols-12 gap-6">
                  
                  {/* Left Column: Link distribution actions */}
                  <div className="md:col-span-7 space-y-4">
                    <div>
                      <span className="text-[10px] font-extrabold text-slate-400 block uppercase">Client Name</span>
                      <span className="font-bold text-slate-800 text-base">{newlyCreatedRequest.clientName}</span>
                    </div>
                    
                    <div>
                      <span className="text-[10px] font-extrabold text-slate-400 block uppercase">Amount Secured</span>
                      <span className="font-black text-indigo-600 text-xl font-mono">R{newlyCreatedRequest.totalDue.toFixed(2)}</span>
                    </div>

                    <div className="space-y-2 pt-2">
                      <span className="text-[10px] font-extrabold text-slate-400 block uppercase">Generated Pay-Link</span>
                      <div className="flex bg-slate-50 border border-slate-200 rounded-xl p-1 items-center">
                        <input
                          type="text"
                          readOnly
                          value={newlyCreatedRequest.payLink}
                          aria-label="Generated Pay-Link text input"
                          className="bg-transparent border-0 flex-1 px-3 text-xs text-slate-600 font-mono focus:outline-none"
                        />
                        <button
                          onClick={() => handleCopy(newlyCreatedRequest.payLink, "newlyCreated")}
                          className="bg-white hover:bg-slate-100 text-indigo-600 p-2 rounded-lg shadow-xs border border-slate-200 transition-all flex items-center gap-1 text-[11px] font-bold"
                        >
                          {copiedId === "newlyCreated" ? (
                            <>
                              <Check className="w-3.5 h-3.5 text-emerald-500" />
                              Copied!
                            </>
                          ) : (
                            <>
                              <Copy className="w-3.5 h-3.5" />
                              Copy
                            </>
                          )}
                        </button>
                      </div>
                    </div>

                    {/* Interactive Simulator Button for simulation convenience */}
                    <div className="flex flex-col gap-2 pt-4 border-t border-slate-100">
                      <button
                        onClick={() => handleMarkAsPaid(newlyCreatedRequest.id)}
                        className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-2.5 px-3 rounded-xl text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition-all shadow-md shadow-emerald-50"
                      >
                        <CheckCircle2 className="w-4 h-4" /> Simulate Client Settle (Mark as Paid)
                      </button>
                      <p className="text-[10px] text-slate-400 italic text-center font-medium">Click to instantly simulate client paying via this link!</p>
                    </div>

                  </div>

                  {/* Right Column: Visual Channel Mockups */}
                  <div className="md:col-span-5 flex flex-col justify-center items-center bg-slate-50 border border-slate-200 p-4 rounded-xl">
                    
                    {newlyCreatedRequest.paymentMethodType === "sms" && (
                      /* Mobile SMS text simulator */
                      <div className="w-full">
                        <span className="text-[9px] font-extrabold text-slate-400 block uppercase text-center mb-2">Simulated SMS Preview</span>
                        <div className="bg-white rounded-2xl p-3 shadow-inner border border-slate-200 font-sans max-w-[210px] mx-auto">
                          <div className="flex items-center gap-1.5 border-b border-slate-100 pb-2 mb-2">
                            <Smartphone className="w-4 h-4 text-indigo-600" />
                            <span className="text-[9px] font-black text-slate-800 uppercase tracking-widest">Zen-i Notify</span>
                          </div>
                          <div className="bg-slate-100 text-slate-800 text-[10px] p-2.5 rounded-2xl leading-normal relative rounded-tl-xs">
                            Zen-i: Hi {newlyCreatedRequest.clientName}, {newlyCreatedRequest.merchantName} has sent you a secure checkout request for <strong>R{newlyCreatedRequest.totalDue.toFixed(2)}</strong>. Pay in 4 split installments: {newlyCreatedRequest.payLink}
                          </div>
                          <div className="text-[8px] text-slate-400 text-right mt-1.5">Delivered via Zen-i SMS</div>
                        </div>
                      </div>
                    )}

                    {newlyCreatedRequest.paymentMethodType === "qr" && (
                      /* QR Generator preview */
                      <div className="w-full text-center">
                        <span className="text-[9px] font-extrabold text-slate-400 block uppercase text-center mb-2">Invoice QR Code scan</span>
                        <div className="bg-white p-3 rounded-xl shadow-sm border border-slate-200 max-w-[180px] mx-auto">
                          {qrDataUrl ? (
                            <img
                              src={qrDataUrl}
                              alt="Secure Invoice QR"
                              className="w-32 h-32 mx-auto object-contain"
                            />
                          ) : (
                            <div className="w-32 h-32 mx-auto bg-slate-50 flex items-center justify-center text-slate-400 text-[10px] animate-pulse">
                              Generating...
                            </div>
                          )}
                          <p className="text-[8.5px] text-slate-400 font-mono mt-2 truncate">{newlyCreatedRequest.payLink}</p>
                        </div>
                      </div>
                    )}

                    {newlyCreatedRequest.paymentMethodType === "link" && (
                      /* Simple Link box mockup */
                      <div className="w-full text-center py-4">
                        <div className="w-12 h-12 rounded-full bg-indigo-50 text-indigo-600 flex items-center justify-center mx-auto mb-2">
                          <ExternalLink className="w-6 h-6" />
                        </div>
                        <h5 className="font-extrabold text-xs text-slate-800">Copy & Email/Chat</h5>
                        <p className="text-[10px] text-slate-400 mt-1">This checkout payload is fully encoded and shareable via any messaging app.</p>
                      </div>
                    )}

                  </div>
                </div>
              </div>
            ) : null}

            {/* Secure Transaction Ledger Table Card */}
            <div className="bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden">
              
              <div className="p-5 border-b border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-50/50">
                <div>
                  <h3 className="font-bold text-sm text-slate-800">Secure Payment Request CRM Ledger</h3>
                  <p className="text-[11px] text-slate-400 mt-0.5">Real-time status tracking and customer payment simulation controls</p>
                </div>
                
                {/* Status Filters */}
                <div className="flex bg-slate-100 p-0.5 rounded-lg border border-slate-200 text-[10px] font-bold uppercase shrink-0">
                  {["All", "Pending", "Paid"].map(status => (
                    <button
                      key={status}
                      onClick={() => setStatusFilter(status as any)}
                      className={`px-2.5 py-1 rounded-md ${statusFilter === status ? "bg-white text-indigo-600 shadow-xs" : "text-slate-500"}`}
                    >
                      {status}
                    </button>
                  ))}
                </div>
              </div>

              {/* Search query box */}
              <div className="p-3 bg-white border-b border-slate-100 flex items-center gap-2">
                <Search className="w-4 h-4 text-slate-400 ml-2" />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search by client name or invoice code (PAY-...)"
                  aria-label="Search payment requests"
                  className="bg-transparent border-0 text-xs text-slate-600 placeholder-slate-400 w-full focus:outline-none"
                />
              </div>

              {/* Ledger Listing */}
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="border-b border-slate-100 text-[9px] font-extrabold uppercase tracking-wider text-slate-400 bg-slate-50/30">
                      <th className="py-3 px-4">Invoice ID</th>
                      <th className="py-3 px-4">Client Name</th>
                      <th className="py-3 px-4">Value (ZAR)</th>
                      <th className="py-3 px-4">Delivery</th>
                      <th className="py-3 px-4">Status</th>
                      <th className="py-3 px-4 text-right">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 text-xs">
                    {filteredRequests.length === 0 ? (
                      <tr>
                        <td colSpan={6} className="py-8 text-center text-slate-400 font-medium">No payment requests match the search filters.</td>
                      </tr>
                    ) : (
                      filteredRequests.map(req => (
                        <tr key={req.id} className="hover:bg-slate-50/50 transition-all font-medium">
                          <td className="py-3.5 px-4 font-mono font-bold text-slate-800">{req.id}</td>
                          <td className="py-3.5 px-4 text-slate-800">
                            <div>
                              <p className="font-bold">{req.clientName}</p>
                              <p className="text-[10px] text-slate-400 font-semibold">{req.merchantName}</p>
                            </div>
                          </td>
                          <td className="py-3.5 px-4 font-bold text-slate-800">R{req.totalDue.toFixed(2)}</td>
                          <td className="py-3.5 px-4 text-slate-500 font-semibold uppercase text-[10px]">
                            <span className="flex items-center gap-1">
                              {req.paymentMethodType === "sms" && (
                                <>
                                  <Smartphone className="w-3 h-3 text-indigo-500" />
                                  SMS
                                </>
                              )}
                              {req.paymentMethodType === "qr" && (
                                <>
                                  <QrCode className="w-3 h-3 text-indigo-500" />
                                  QR Code
                                </>
                              )}
                              {req.paymentMethodType === "link" && (
                                <>
                                  <ExternalLink className="w-3 h-3 text-indigo-500" />
                                  Link
                                </>
                              )}
                            </span>
                          </td>
                          <td className="py-3.5 px-4">
                            <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-extrabold uppercase ${
                              req.status === "Paid"
                                ? "bg-emerald-50 text-emerald-700 border border-emerald-200"
                                : "bg-indigo-50 text-indigo-700 border border-indigo-200"
                            }`}>
                              {req.status === "Paid" ? (
                                <>
                                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
                                  Settled
                                </>
                              ) : (
                                <>
                                  <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 animate-pulse"></span>
                                  Pending
                                </>
                              )}
                            </span>
                          </td>
                          <td className="py-3.5 px-4 text-right">
                            <div className="flex items-center justify-end gap-1.5">
                              <button
                                onClick={() => setSelectedRequestForQr(req)}
                                className="bg-indigo-50 hover:bg-indigo-100 text-indigo-700 px-2 py-1 rounded text-[10px] font-extrabold uppercase tracking-wide transition-all inline-flex items-center gap-1"
                                title="Generate actual QR code"
                              >
                                <QrCode className="w-3 h-3" />
                                QR Code
                              </button>
                              <button
                                onClick={() => handleCopy(req.payLink, req.id)}
                                className="bg-slate-100 hover:bg-slate-200 text-slate-700 px-2 py-1 rounded text-[10px] font-extrabold uppercase tracking-wide transition-all inline-flex items-center gap-1"
                              >
                                {copiedId === req.id ? (
                                  <>
                                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                                    Copied
                                  </>
                                ) : (
                                  <>
                                    <Copy className="w-3.5 h-3.5" />
                                    Copy Link
                                  </>
                                )}
                              </button>
                              {req.status === "Pending" ? (
                                <button
                                  onClick={() => handleMarkAsPaid(req.id)}
                                  className="bg-indigo-600 text-white hover:bg-indigo-700 px-2 py-1 rounded text-[10px] font-extrabold uppercase tracking-wide transition-all inline-flex items-center gap-1"
                                >
                                  Mark Paid
                                </button>
                              ) : (
                                <span className="text-[10px] text-emerald-600 font-extrabold uppercase tracking-wider block px-2 py-1">
                                  ✓ Settled
                                </span>
                              )}
                            </div>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>

              {/* Bottom Ledger stats banner */}
              <div className="p-4 bg-slate-50 border-t border-slate-100 grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
                <div>
                  <span className="text-[9px] font-extrabold text-slate-400 block uppercase">Generated Value</span>
                  <span className="font-extrabold text-sm text-slate-800">R{totalGeneratedAmt.toFixed(2)}</span>
                </div>
                <div>
                  <span className="text-[9px] font-extrabold text-slate-400 block uppercase">Settled Invoices</span>
                  <span className="font-extrabold text-sm text-emerald-600">R{totalCollectedAmt.toFixed(2)}</span>
                </div>
                <div>
                  <span className="text-[9px] font-extrabold text-slate-400 block uppercase">Outstanding Book</span>
                  <span className="font-extrabold text-sm text-indigo-600">R{totalPendingAmt.toFixed(2)}</span>
                </div>
                <div>
                  <span className="text-[9px] font-extrabold text-slate-400 block uppercase">Link Settlement</span>
                  <span className="font-extrabold text-sm text-indigo-600">{conversionRate.toFixed(0)}% Settle</span>
                </div>
              </div>

            </div>

          </div>

        </div>

      </div>

           {/* Modern Clean Website Footer */}
      <footer className="py-8 bg-white border-t border-slate-200 px-6 md:px-10 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 gap-4 mt-12 shrink-0">
        <div>
          <span className="font-semibold text-slate-800">Apparel Co.</span> — Powered by Zen-i Payments
        </div>
        <div className="flex gap-6 text-slate-400 font-medium">
          <span>Secure Checkout</span>
          <span>Terms of Service</span>
          <span>Privacy Policy</span>
        </div>
      </footer>

      {/* Dynamic QR Code Modal for Selected Invoice */}
      {selectedRequestForQr && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl border border-slate-100 max-w-md w-full shadow-2xl overflow-hidden">
            <div className="bg-indigo-950 text-white p-6 flex justify-between items-center">
              <div>
                <span className="text-[10px] font-extrabold text-indigo-300 uppercase tracking-wider block">Live Invoice QR Generator</span>
                <h4 className="text-base font-bold">{selectedRequestForQr.clientName}</h4>
              </div>
              <button
                onClick={() => setSelectedRequestForQr(null)}
                className="text-slate-300 hover:text-white bg-indigo-900 hover:bg-indigo-800 p-2 rounded-xl text-xs font-bold transition-all"
              >
                Close Window
              </button>
            </div>
            <div className="p-6 flex flex-col items-center justify-center text-center space-y-4">
              <p className="text-slate-500 text-xs font-semibold">
                Scan with any mobile bank app or camera to settle this <strong>{storeName}</strong> invoice directly on Zen-i.
              </p>
              
              <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200 shadow-inner">
                {selectedQrDataUrl ? (
                  <img
                    src={selectedQrDataUrl}
                    alt="Active Invoice QR"
                    className="w-56 h-56 mx-auto object-contain"
                  />
                ) : (
                  <div className="w-56 h-56 mx-auto bg-slate-100 animate-pulse rounded flex items-center justify-center text-[10px] text-slate-400">
                    Generating secure QR...
                  </div>
                )}
                <p className="text-[9px] font-mono font-bold text-slate-400 mt-3 truncate max-w-[280px]">
                  {selectedRequestForQr.payLink}
                </p>
              </div>

              <div className="bg-indigo-50/50 border border-indigo-100 rounded-xl p-3 w-full flex justify-between items-center text-xs">
                <div className="text-left">
                  <span className="text-[10px] font-extrabold text-slate-400 uppercase tracking-widest block">Reference Code</span>
                  <span className="font-mono font-black text-indigo-900 text-sm">{selectedRequestForQr.id}</span>
                </div>
                <div className="text-right">
                  <span className="text-[10px] font-extrabold text-slate-400 uppercase tracking-widest block">Total Settling (ZAR)</span>
                  <span className="font-extrabold text-indigo-700 text-sm">R{selectedRequestForQr.totalDue.toFixed(2)}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
